### ISSUE TITLE
toggleterm strategy doesn't close the float window when lost focus

### ISSUE THREAD

**Issue by meijieru** [stevearc/overseer.nvim#100]
I have the following settings
```lua
    strategy = { "toggleterm", open_on_start = true },
```
When in the toggleterm default float term, I would move to another window to close the float win.
While the float term opened by overseer doesn't.
The terminal window opened in the task menu through `<c-f>` could.

BTW, how could we set `open_on_start` behavior for individual templates, both through lua & json?

**Comment by stevearc** [comment]
I don't personally use toggleterm, but here's my best guess. I used this minimal config to try to reproduce the issue:
```lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

vim.g.mapleader = " "
vim.keymap.set("t", "\\\\", [[<C-\><C-N>]])

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "akinsho/toggleterm.nvim",
    opts = {
      open_mapping = [[<C-\>]],
      direction = "float",
    },
  },
  {
    "stevearc/overseer.nvim",
  opts = {
    strategy = { "toggleterm", open_on_start = true },
  }
  }
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
```

I noticed that toggleterm windows that still have a running process (the task is still running, or the shell is still active) will automatically close when you leave the window. If the process is no longer running, then when you leave the window it will remain. I'm not sure why there is a difference, but this sounds like intentional behavior from toggleterm. You can test this in isolation by sourcing the following file:

```lua
local terminal = require("toggleterm.terminal")

local term = terminal.Terminal:new({
  cmd = "sleep 6",
  direction = 'float',
  close_on_exit = false,
})

term:toggle()
```

> BTW, how could we set open_on_start behavior for individual templates, both through lua & json?

There's no way to do this from json yet. Theoretically this sort of thing could be controlled by the [output behavior](https://code.visualstudio.com/docs/editor/tasks#_output-behavior), but I haven't added support for that.

From lua, you can override the strategy on a per-task basis. Simply pass in `strategy = {"toggleterm", open_on_start = true}` with any task and change the value of `open_on_start` as you like.

**Comment by meijieru** [comment]
> From lua, you can override the strategy on a per-task basis.

Thanks for the information!
