### ISSUE TITLE
Running a task never executes the command on windows/powershell when the builder returns cmd as a table

### ISSUE THREAD

**Issue by Kamholtz** [stevearc/overseer.nvim#101]
# Problem:

When the template definition has a builder which returns "cmd" as a table, it does not execute as expected. I am using powershell.

# Configuration:

I have neovim configured to use powershell using the recommended settings in `:h shell-powershell`. For reference:

```
*shell-powershell*
	To use PowerShell:  
		let &shell = executable('pwsh') ? 'pwsh' : 'powershell'
		let &shellcmdflag = '-NoLogo -NoProfile -ExecutionPolicy RemoteSigned -Command [Console]::InputEncoding=[Console]::OutputEncoding=[System.Text.Encoding]::UTF8;'
		let &shellredir = '2>&1 | Out-File -Encoding UTF8 %s; exit $LastExitCode'
		let &shellpipe = '2>&1 | Out-File -Encoding UTF8 %s; exit $LastExitCode'
		set shellquote= shellxquote=

 	This option cannot be set from a |modeline| or in the |sandbox|, for
	security reasons.
```

Setup (I use fennel. I suspect it's easy enough to read but I can try provide it in lua if necessary):

```fnl
(overseer.setup {})
```

Template:

(note, ["ls"] in fennel is equivalent to {"ls"} in lua.

```fnl
(overseer.register_template {:name "ls with table"
                             :builder (fn [params] 
                                        {:cmd ["ls"]
                                         :args []
                                         :name "ls with table"
                                         :env {}
                                         :strategy {1 :jobstart :use_terminal false}
                                         })})

(overseer.register_template {:name "ls without table"
                             :builder (fn [params] 
                                        {:cmd "ls"
                                         :args []
                                         :name "ls without table"
                                         :env {}
                                         :strategy {1 :jobstart :use_terminal false}
                                         })})
```

Output in tasklist after using `OverseerRun` and selecting "ls with table":

```bash
PENDING: ls with table
```

Output in tasklist after using `OverseerRun` and selecting "ls without table":

```bash
SUCCESS: ls without table
out: -a----        27/01/2023   1:04 PM           2176 shadow-cljs.edn                                                      
```

Different strategies yield slightly different results, but none work as expected. 

`strategy = toggleterm`:

```bash
ls

[Process exited 0]
```

`strategy = terminal` results in the tab going completely blank.

**Comment by stevearc** [comment]
This is interesting, because according to `:help jobstart()` passing a list instead of a string should ignore the shell entirely. If you open neovim and run `:call termopen(['ls'])`, what happens?

Oh also, what do you see in the overseer log? You can find the path to the log files with `:echo stdpath('log')` (or on older version of Neovim, `:echo stdpath('cache')`).

**Comment by Kamholtz** [comment]
Thank you for looking into this!

When running `ls with table` with OverseerRun, the following is written to overseer's log:

```
[ERROR] Strategy 'jobstart' failed to start for task 'ls with table': Vim:E475: Invalid value for argument cmd: 'ls' is not executable
```

Executing `:call termopen(["ls"])` produces the message:

```
E475: Invalid value for argument cmd: 'ls' is not executable
```

Executing `:call termopen("ls")` produces the correct output of the `ls` command.


I also tried removing the powershell config mentioned in the original post so that `shell="cmd.exe"`

`:call termopen(['dir'])` produces 

```
E475: Invalid value for argument cmd: 'dir' is not executable
```

Executing `:call termopen('dir')` produced the correct output in the current window.

So it appears not to be powershell exclusive.

**Comment by stevearc** [comment]
I don't develop on Windows anymore and never learned much about the internals of the shell or OS, so I can't say anything very authoritatively, but here's my best shot. My guess is that "ls" and "dir" are not executables, but built in to the shell. When you run a job or terminal with an array, vim bypasses the shell entirely and tries to run the command as an executable, which fails. This is simply how the system is designed; a command string is intentionally handled differently than a command array. If you need to run a command using the shell, you'll need to pass in a string. You _can_ still pass arguments as an array in the `args` parameter, but the `cmd` value will need to be a string.

**Comment by Kamholtz** [comment]
Sounds plausible!  I tested the following:

```fnl
(overseer.register_template {:name "where.exe with table"
                             :builder (fn [params] 
                                        {:cmd ["where.exe"]
                                         :args ["where.exe"]
                                         :name "where.exe with table"
                                         :env {}
                                         :strategy {1 :jobstart :use_terminal false}
                                         })})

```

which produced the correct output, the location of the `where.exe` executable.



It didn't seem to work with `strategy = toggleterm` though:

```fnl
(overseer.register_template {:name "where.exe with table, strategy = toggleterm"
                             :builder (fn [params] 
                                        {:cmd ["where.exe"]
                                         :args ["where.exe"]
                                         :name "where.exe with table, strategy = toggleterm"
                                         :env {}
                                         :strategy :toggleterm
                                         })})
```

Result of the above sample:

```
At line:1 char:94
+ ... ncoding=[System.Text.Encoding]::UTF8; "where.exe" "where.exe";#toggle ...
+                                                       ~~~~~~~~~~~
Unexpected token '"where.exe"' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken

```

On the other hand, using `strategy = terminal` produces the correct result.

```fnl
(overseer.register_template {:name "where.exe with table, strategy = terminal"
                             :builder (fn [params] 
                                        {:cmd ["where.exe"]
                                         :args ["where.exe"]
                                         :name "where.exe with table, strategy = terminal"
                                         :env {}
                                         :strategy :terminal
                                         })})

```

**Comment by stevearc** [comment]
Glad to hear the first-party strategies are working as expected. The toggleterm integration is having issues due to the confluence of a few factors. The first is that it does not really support passing in a table. When you create the terminal, you must pass a string and it will then be concatted into a table that is passed to `termopen`. So the API for that operation is just not available.

https://github.com/akinsho/toggleterm.nvim/blob/557664818f6af78de6192f0ce8bc2e887bf4943a/lua/toggleterm/terminal.lua#L371-L378

We try to make it work regardless by shell-escaping the table and passing it in as a single string. This seems to work in Unix, but I guess it has issues in Windows.

https://github.com/stevearc/overseer.nvim/blob/65663aedb76779ee6daa6f0a89806ac2474c2fba/lua/overseer/strategy/toggleterm.lua#L68-L71

As I don't use toggleterm or Windows personally, and my time is pretty limited these days, I probably won't be making any changes to this myself. I'd be happy to review a PR if you find a way to improve the behavior!

**Comment by Kamholtz** [comment]
I am content with using the other strategies for now. Thank you for your assistance, I think this discussion will be helpful if someone else decides to take on the challenge.

**Comment by Tired-Fox** [comment]
The issue is that the arguments are escaped and wrapped with quotes, `"`. Powershell doesn't understand the shell escaped tokens. So a solution would be to have none of the components of the cmd escaped. I propose something like this.
```lua
  local cmd = task.cmd
  if type(task.cmd) == "table" then
    if package.config:sub(1,1) == '\\' then
      cmd = table.concat(task.cmd, " ")
    else
      cmd = table.concat(vim.tbl_map(vim.fn.shellescape, task.cmd), " ")
    end
    print(cmd)
  end
```
It will only apply the non escaping logic if the user is on windows otherwise it stays as is since it works on other platforms.

I plan to open a PR for this change.
