### ISSUE TITLE
Errorformat tsc

### ISSUE THREAD

**Issue by mattiasbonte** [stevearc/overseer.nvim#114]
Hello!

I'm trying out this cool but more advanced plugin. But I can't seem to produce any results with the custom `"on_output_quickfix" -> errorformat` command. Passing `%f` works, but then it gives me the whole error log. I'm apparently not able to really refine it deeper.

I want to implement the already working `errorformat` from withing the [official tsc compiler in the vim repo](https://github.com/vim/vim/blob/f06c4a7a1d6a8a02449e6ed3aa3a2c19d7fde2ea/runtime/compiler/tsc.vim#L21-L23).

I'm not able to produce any results using the same approach as showcased in the [cargo template here](https://github.com/stevearc/overseer.nvim/blob/979f93c57885739f1141e37542bad808a29f7a9a/lua/overseer/template/cargo.lua#L18).

This is an example of what I tried. I'm running the `tsc --watch` command here.
```lua
{
	"on_output_quickfix",
	open = not params.bang,
	close = true,
	items_only = true, -- only show items, not errors
	open_height = 8,
	open_on_match = true,
	set_diagnostics = true,
	tail = true,
	errorformat = [[%f\ %#(%l\\,%c):\ %trror\ TS%n:\ %m,]]
		.. [[\%trror\ TS%n:\ %m,]]
		.. [[\%-G%.%#]]
},
```
![output](https://user-images.githubusercontent.com/65280774/223284364-354dfd1b-cbd9-4dc8-bd08-49e14aa9058a.png)

I don't want to post all examples but I've tried a lot of things :P.
`"%f(%l,%c): %trror TS%%d: %%m,%f(%l,%c): %tarning TS%%d: %%m,%-G%.%#",`
`"%f:%l:%c: - %t TS%n: %m",`
`"%f"` -- this works.. kinda. But outputs the whole error log.

Any ideas to what I might be doing wrong?

-----

There is also a second part to the question. When running the command above with tail set to true, it indeed tails the output as expected. But I was wondering if it would be possible to somehow clear the quickfix menu every time the watch command does a rebuild and produces an updated list of errors. Its quite cumbersome to have have the qf list being populated with all the past errors as well. I'd like it to only show the active errors at all time. Do you think this is possible? Did I miss this option? Or does it not yet exist inside the current scope of the plugin? 

To give a bit more context, I wish to have my `tsc --watch` command output all the active error every time a change has been spotted. Right now it also outputs the compilation messages and the history of all previous messages. With the first part of my question I'm trying to filter out these compilation messages. And with the second part I'm trying to filter out the old errors from the qflist whenever the watch command reloads.

![image](https://user-images.githubusercontent.com/65280774/223287998-428271de-1b9c-4277-8763-1e416d614e83.png)

-----

If there is a better way to achieve this, I'm definitely all eyes and ears :).

Thank you very much for your time...

**Comment by leonardmorgan** [comment]
I also got errors using the built-in problem matchers. I use $gcc and the error says something about “autoDetect not found"

**Comment by stevearc** [comment]
So there's the question you're asking: "how can I use on_output_quickfix and errorformat to parse the output of `tsc --watch`, and clear the quickfix whenever it restarts"
And there's the implicit question of "I want to parse the output of `tsc --watch` and clear the quickfix when it restarts. How can I best do this?"

It is easier to answer the second one, because there are better tools for this available that _don't_ use `on_output_quickfix` and errorformat, but if you _do_ really want to use that implementation let me know, because it is possible it's just more work right now.

## Option 1: VS Code tasks.json format
Turns out this is a common task for people that use VS Code, and so there are pretty good builtins for handling it. Create a `.vscode/tasks.json` file and add the following contents:
```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "shell",
      "command": "tsc --watch",
      "problemMatcher": "$tsc-watch"
    }
  ]
}
```
This will launch `tsc --watch` and parse the output. Each time it detects changes a re-runs, we'll clear the diagnostics & quickfix and repopulate the results. The `default_vscode` component alias should contain both `on_result_diagnostics`, which will put the parsed results into vim.diagnostic, and `on_result_diagnostics_quickfix`, which will put them into the quickfix list.

## Option 2: Define in lua

Here's an example of the same task defined in lua:
```lua
overseer.register_template({
  name = "tsc --watch",
  builder = function()
    return {
      cmd = { "tsc", "--watch" },
      components = {
        "default",
        { "on_output_parse", problem_matcher = "$tsc-watch" },
        "on_result_diagnostics",
        "on_result_diagnostics_quickfix",
      },
    }
  end,
})
```
This is still using VS Code's problem matchers for parsing the output. If you want to define your own using a [parser](https://github.com/stevearc/overseer.nvim/blob/master/doc/parsers.md) instead of a problem_matcher, that will be a more involved process. The translation from problem_matcher-to-parser makes use of [parser.lib.watcher_output](https://github.com/stevearc/overseer.nvim/blob/master/lua/overseer/parser/lib.lua), which you can re-use to get the same structure.

**Comment by mattiasbonte** [comment]
Hey Steve!

Option 2 is exactly what I wanted. I feel like there is so much possible with this plugin, but for now that's all I needed. 

Thanks a lot for your detailed reply.
