### ISSUE TITLE
How to summarize the result

### ISSUE THREAD

**Issue by meijieru** [stevearc/overseer.nvim#117]
The `on_complete_callback` is deprecated, then how could we summarize the result?
The deprecated_message says we should use `task:subscribe` instead. But how can we access the task within the template?

**Comment by stevearc** [comment]
I'm not sure what you mean by "summarize the result", but you can see a couple of examples of `subscribe` in use in the `DAP` handler:
https://github.com/stevearc/overseer.nvim/blob/ca30db070744f3c768aef3b1bd9849e2e870b797/lua/overseer/dap.lua#L79-L80

The first argument to the callback function will be the task itself, so you have direct access to it.

**Comment by meijieru** [comment]
I already extract the `result` with the parser and want to apply some transformations to the `result` for notification & setting the quickfix.
Ideally, we could have a pipeline for processing the `result`, like a `dispatch` component.

Thanks for the example, would take a look.

**Comment by stevearc** [comment]
Hmmmm...that's a little bit tricky. We use `on_pre_result` to compile the result object from all the components (this is what fetches it from the parser), then we call `on_result` to send it to components like `on_result_diagnostics_quickfix`. There's no intermediate step at the moment, and I'd like to avoid adding one if possible just to keep the event logic from becoming even more complex.

What sort of processing do you need to do on the results? The way I've handled this in the past is by ensuring that the parser produces items in the format I expect. If it's possible to do that for your use case, that would probably be the easiest route.

**Comment by meijieru** [comment]
I have a list of servers for sync. The result is a list of tables with keys `server`, and `status`.
To summarize them, I would like to notify the number of successful sync.
I don't find a way to parse into it directly. Also, I would dump the details into quickfix. So I would apply different transformations for the result.

**Comment by stevearc** [comment]
Okay, I think that the only decent solution for your use case is to add another event then. I've added `on_preprocess_result` which can be used either by a component or subscribed to. An example:

```lua
task:subscribe("on_preprocess_result", function(task, result)
  -- update `result` in-place
end)
```

**Comment by meijieru** [comment]
Thanks!

**Comment by meijieru** [comment]
In terms of the `on_preprocess_result`, would it be natural to return a new result instead of modifying it in place?

**Comment by stevearc** [comment]
I have a slight preference to keep it as a mutation-in-place. In contrast to `on_pre_result` which is _creating_ the result object, this handler is intended to _mutate_ the result. I think the in-place nature of this call reinforces that idea.

**Comment by meijieru** [comment]
`self.result = on_preprocess_result(comp, task, result)` does the same thing?
Also, in-place table modification is much more inconvenient than the above.
For example, you must copy the table, process, clear the original table, and assign.

**Comment by stevearc** [comment]
It's important to remember that these are not simple function calls, but rather event dispatches. As such, there can be 0, 1, or many return values. This is reasonable for `on_pre_result` because we [gather all the results](https://github.com/stevearc/overseer.nvim/blob/b5f1632ecb7f730b4726f2b3126971aad0928643/lua/overseer/task.lua#L487-L489) and merge them into a single object. (You can see that Task:dispatch [aggregates the return values](https://github.com/stevearc/overseer.nvim/blob/b5f1632ecb7f730b4726f2b3126971aad0928643/lua/overseer/task.lua#L446-L451) and returns the table). That is fine when we are creating an object, but much less fine when we expect to mutate an object.

I am confused by your statement that in-place modification requires a "copy, process, clear, assign" operation. In-place modification doesn't require any copying, nor do I see how it could be less convenient than the alternative. Want to replace a key? `result.mykey = 'newvalue'`. Want to clear a key? `result.mykey = nil`.
