### ISSUE TITLE
Preview output has a lot of extra lines

### ISSUE THREAD

**Issue by petobens** [stevearc/overseer.nvim#141]
Hi! After https://github.com/stevearc/overseer.nvim/commit/2227cbeb0b1a46a4fc3bbf12d897ad4863c9c2df was merged if, as in the GIF, I scroll the preview window I see a lot "empty lines":  I would expect the last line to be the one with `[Process exited 1]` but I can scroll way past it.

Unrelated/bonus: I see the tasklist buffer reports `[No Name]` in the statusline; is it possible to give it a name or remove the name all together?

![overeseer_scroll](https://github.com/stevearc/overseer.nvim/assets/2583971/c6d4e518-41d1-4702-9dd4-279a2876449f)

**Comment by stevearc** [comment]
This is unfortunately just a byproduct of how the terminal buffers work. They sometimes have a lot of blank lines on the end to pad out the height (see https://github.com/neovim/neovim/issues/9226). It's possible that once terminal reflow is supported the buffer will resize itself to better fit the containing window.

As for the "[No Name]", it's because the buffer doesn't have a name. Whatever your statusline plugin is, that display should be customizable. You should be able to display whatever you want there if `filetype == "OverseerList"`, but you'd have to read the docs for it to find out how.

**Comment by petobens** [comment]
Thanks for the explanation!
