### ISSUE TITLE
Cannot silence statuses on_complete_notify

### ISSUE THREAD

**Issue by petobens** [stevearc/overseer.nvim#143]
HI I have a custom template that looks like:
```lua
return {
    name = 'run_python',
    builder = function()
        local file = vim.fn.expand('%:p')
        local cmd = { 'python' }
        return {
            cmd = cmd,
            args = { file },
            metadata = { run_cmd = string.format('%s %s', cmd[1], file) },
            components = {
                'default',
                { 'on_output_quickfix', tail = false, open = false },
                { 'on_complete_notify', statuses = { 'FAILURE' } },
            },
            default_component_params = {
                errorformat = PYTHON_EFM,
            },
        }
    end,
    condition = {
        filetype = { 'python' },
    },
}
```
I want to avoid having a `SUCCESS` notification. However, as it can be seen in the GIF, when I call the above template I still get such notification. Clearly I'm doing something wrong but cannot figure out what it is. Thanks in advance.

![overseernot](https://github.com/stevearc/overseer.nvim/assets/2583971/d6498079-5c82-4075-92d0-e54beea50c5f)

**Comment by stevearc** [comment]
Yep, first let me explain how you can debug what's happening, or at least rule some things out. The first thing I would think of is "what are the actual values on the component?" We can use that to determine if it's a bug in the component or an issue with setting the values. There's two ways to do this.

First: open the task list with `:OverseerOpen`. Now you can either show the maximally detailed view of the tasks by pressing `<C-l>` twice (there are three detail levels. `<C-h>` decreases the detail level), or you can edit the task by selecting it (`<CR>`) and choosing the `edit` action. This will open a read/write view of the task and components.

You'll notice that the list of statuses shows both `SUCCESS` and `FAILURE`. So it's not a bug in the component, it's an issue with setting the correct parameters.

From here, I will admit there's not a great way to figure out what's happening without some trial-and-error. One thing you could try is inlining the `default` components. If you look at the docs on [setup options](https://github.com/stevearc/overseer.nvim/blob/master/doc/reference.md#setup-options) you'll find the default values for the `default` component alias:
```lua
components = {
    { "display_duration", detail_level = 2 },
    "on_output_summarize",
    "on_exit_set_status",
    "on_complete_notify",
    "on_complete_dispose",
    { 'on_output_quickfix', tail = false, open = false },
    { 'on_complete_notify', statuses = { 'FAILURE' } },
}
```

Okay, so `on_complete_notify` appears twice. What happens if we get rid of the duplicate?

```lua
components = {
    { "display_duration", detail_level = 2 },
    "on_output_summarize",
    "on_exit_set_status",
    "on_complete_dispose",
    { 'on_output_quickfix', tail = false, open = false },
    { 'on_complete_notify', statuses = { 'FAILURE' } },
}
```

aaaaand it works now. What's going on?

Well, if you add a component to a task twice one of two things is going to happen: either the first component "wins" or the second component "wins" (or we throw an error, but I opted to not do that). For overseer, I decided that the adding a duplicate component should no-op, so the first component has priority. I've finally gotten around to documenting this [in a new section on component aliases](https://github.com/stevearc/overseer.nvim/blob/master/doc/guides.md#component-aliases).

So the final answer to your question is: if you want to set _specific_ components on a task, specify them _before_ you add the `default` component alias.

```lua
components = {
    { 'on_complete_notify', statuses = { 'FAILURE' } },
    "default"
}
```
