### ISSUE TITLE
Support smaller-font next line view of detail in displaying the tasks from vscode tasks

### ISSUE THREAD

**Issue by krishnakumarg1984** [stevearc/overseer.nvim#147]
The VSCode tasks picker appears as follows:

![image](https://github.com/stevearc/overseer.nvim/assets/15239509/88d62751-4059-42cb-874d-44b5b3714037)

whereas neovim with overseer shows as following:

![image](https://github.com/stevearc/overseer.nvim/assets/15239509/18968a4e-5857-4f81-b33f-8675ebbb0104)

When there is significant amount of text in the "detail" field of the task, it becomes difficult to understand if it is shown in the same font size on the same line. Long lines of detail also gets chopped off.

Would it be possible to adopt VSCode's style for displaying?

**Comment by stevearc** [comment]
Unfortunately not. We're using `vim.ui.select` for choosing a task, and it doesn't have any sort of API for passing in "detail information". Furthermore, all of the `vim.ui.select` implementation I'm aware of (e.g. fzf, telescope) are built for single-line entries. They don't have any way to do what you describe.

Also worth noting that since Neovim runs in the terminal, there's no way to render in different font sizes. There are exceptions of course: [neovide](https://github.com/neovide/neovide) is a gui and could use multiple font sizes, and [kirby.nvim](https://github.com/romgrk/kirby.nvim) could potentially do that as well using the kitty graphics protocol.

**Comment by lavish440** [comment]
Some colorschemes have a way of displaying Italicized text. Maybe that could be implemented here as well
