### ISSUE TITLE
Clarification on template parameters

### ISSUE THREAD

**Issue by sawwheet** [stevearc/overseer.nvim#18]
Hey, want to lead off by saying this is a very impressive plugin!

And I apologize, this is less of an issue and more of a question, as im having difficulties understanding how to manage parameters.

What i am trying to do is make a `go run` template, and that template can optionally accept arguments, ie `go run main.go -f my-flag`, or just `go run main.go`.

However, if i mark the parameter as optional, the input box doesnt show up. If I mark the parameter as required, i cant run the program with no argmuents (go run main.go), the input box flashed red when i attempt to leave it empty.

I also noticed that the `shell` command has optional params as well, but they dont show up when running the shell template. Overall I am confused by how to utilize these optional params. 

Thanks for any input, and the extensive and well designed plugin!

**Comment by stevearc** [comment]
No worries! The documentation is a work in progress; there's a lot to understand and not all of it is even formally documented.

What you're looking for is the `prompt` option of the `run_template` function (which is called by `:OverseerRun`)
https://github.com/stevearc/overseer.nvim/blob/62ce37e8b805a12dfa94630f0b77735e830cbde3/lua/overseer/commands.lua#L94-L98

The default is "allow", which will _allow_ the prompt to be shown if any required parameters are missing. The behavior that you want is probably "missing", which will show the input box if any listed params are not explicitly passed in. Changing this value currently requires you to call the [run_template](https://github.com/stevearc/overseer.nvim/blob/62ce37e8b805a12dfa94630f0b77735e830cbde3/lua/overseer/init.lua#L273) function directly so you can pass in the `prompt` option. I remember earlier I wanted to add a config option to allow people to change the default behavior so that it could affect `:OverseerRun`, but apparently I haven't gotten to it yet. Is that something that would be helpful?

**Comment by sawwheet** [comment]
I see, thank you for the explanation. 

My desired workflow with this is to run `OverseerRun`, choose my task, and be prompted for a list of configured parameters (even if all optional).

I now understand I can directly call `run_template` with `prompt=missing` passed in to have the prompt shown. But is there a way to modify the template itself to ask for parameters, even if only optional ones exist? I would like to continue to have the list selection, rather than call a template directly via `run_template`

**Comment by stevearc** [comment]
Oh, if you call `run_template` without passing in a `name`, it'll show you the task picker. It only skips the picker if you supply a `name`.

As mentioned, I could add a config option to change the default value for `prompt`, but it'll take me a bit of time to get to it. I just got back from vacation and am absolutely flooded with requests

**Comment by cmquinn97** [comment]
Oh I completely misunderstood what run_template did! I think I should be able to get what I want then. 

I'll keep an eye out for any changes you make though. 

Thanks for your response and hope you had a nice vacation

**Comment by sawwheet** [comment]
(Reposting from account i opened this with).

Oh i completely misunderstood what `run_template` did! I think I should be able to get what I want then.

I'll keep an eye out for any changes you make though

Thanks for your response and hope you had a nice vacation

**Comment by stevearc** [comment]
Thanks! I'll actually keep this issue open for tracking. Will close it out once I get the config option in place.

**Comment by stevearc** [comment]
I've added the `default_template_prompt` argument, which you can use to customize the default `prompt` option for `run_template`.
