### ISSUE TITLE
Question on opening the quickfixlist to show errors from a gcc compilation process

### ISSUE THREAD

**Issue by krishnakumarg1984** [stevearc/overseer.nvim#19]
I am coming to Overseer from other task automation tools (asyncrun/asynctasks initially and later on, mg979/tasks.nvim) that load the output from the compilation command onto the quickfix window by parsing the `errorformat`. 

I came to Overseer based on good experience with your other neovim plugins e.g. `aerial`, and was interested in a pure lua plugin for my compilations. Most importantly, the major compatibility with vscode's tasks.json format means that I can mostly reuse the standard json (with some minor modifications) that my colleagues are using.

While the documentation is quite extensive, and it is certainly a well thought out example of high quality software engineering, the documentation is missing simple recipes e.g. building, running and debugging a C++/python/rust application.  While the demo video piqued my interest, it is certainly not satisying the needs of the tutorial. The exhaustive project documentation currently is less tailored to those who simply want to achieve simple end goals.

Here's a specific question. How can I use the following `.vscode/tasks.json` on a simple `helloworld.cpp` (with syntax error missing a semicolon) to automatically populate and open the quickfix window upon building?

**`.vscode/tasks.json`**

```json
{
  "tasks": [
    {
      "type": "shell",
      "label": "g++ debug build: compile active file",
      "command": "g++",
      "args": [
        "-std=c++20",
        "-Wall",
        "-fdiagnostics-color=always",
        "-DDEBUG",
        "-O0",
        "-g",
        "-gdwarf-5",
        "${file}",
        "-o",
        "${fileDirname}/${fileBasenameNoExtension}.x"
      ],
      "problemMatchers": "$cpp",
      "options": {
        "cwd": "${fileDirname}"
      },
      "group": {
        "kind": "build",
        "isDefault": true
      }
    }
  ],
  "version": "2.0.0"
}
```

**helloworld.cpp** (with syntax error, missing a semicolon in the `cout` statement within the loop)

```cpp
#include <iostream>
#include <vector>
#include <string>

int main()
{
    std::vector<std::string> msg{"Hello", "C++"};

    for (const std::string &word : msg)
    {
        std::cout << word << " "
    }
    std::cout << endl;
}
```

**Comment by ranjithshegde** [comment]
There is a PR #4 in the works. Meanwhile you can check out this [custom component ](https://gitlab.com/ranjithshegde/dotbare/-/blob/master/.config/nvim/lua/overseer/component/r/dispatch.lua)that I created based on (but independent of) this PR that does the same. It is a lua table, but you can just convert that to json and put it in your `task.json` file

**Comment by stevearc** [comment]
As Ranjith said, that PR should address this and is in-progress but not finalized. There are some API changes I'd like to make to it before merging. It's been pending for a while because I've had a whole lot going on at work and outside of work, and requests on my open source projects have piled up. Just this last week I've started making headway on the backlog, but I'm out of time again for today. I hope to be able to come back and finish this one up no later than the end of next weekend.

**Comment by krishnakumarg1984** [comment]
@ranjithshegde and @stevearc Thank you for your responses, and thank you for trying to address this request.

I updated the `problemMatcher` to use `$gcc` and rven after updating to the latest commit of `overseer`, I still am not able to make this work. i.e. the quickfix window does not open. In fact, the quickfix window seems to not even contain diagnostics. After `:OverSeerRun` and `:OverSeerToggle!`, I am getting some garbled characters in the overseer split. Please see the screenshot below which hopefully illustrates these problems.

![image](https://user-images.githubusercontent.com/15239509/187666757-8ebc0cac-4757-4f11-93c7-218ea91ec467.png)

**Comment by stevearc** [comment]
Some questions:
* In your initial `tasks.json` file, you used the key `"problemMatchers"` instead of `"problemMatcher"`. Have you corrected that?
* If you expand the task all the way in the overseer list (default bound to `l`), do you see a "problem_matcher: <opaque>" line underneath the `vscode.result_vscode_task` component?
![Screenshot from 2022-08-31 07-29-19](https://user-images.githubusercontent.com/506791/187703852-286c8bed-2045-45e5-a9ce-ec636338b417.png)
* What does the full output of the command look like if you open the terminal?
