### ISSUE TITLE
bug: Overriding the task in a bundle doesn't save the new changes

### ISSUE THREAD

**Issue by s1n7ax** [stevearc/overseer.nvim#223]
### Neovim version (nvim -v)

NVIM v0.9.1

### Operating system/version

NixOS 23

### Describe the bug

When some updates has been made to a task using edit, overriding the task does not save the changes unless the task bundle name is given when updating. When the bundle name is empty, it still prompts to override or append, however, overriding does not save the changes

### Steps To Reproduce

1. Create task using `OverseerRun`
2. Add `echo 'test'` as the command
3. Run the command
4. Save the command under the bundle `hello`
5. Edit the task to `echo 'hello world'`
6. Save the task by giving empty string to the bundle name
7. Select override from the prompt
8. Close and reopen Neovim
9. Load the `hello` bundle
10. Run the task

### Expected Behavior

Task should print `'hello world'`but it is `'test'`

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "stevearc/dressing.nvim", config = true },
  {
    "stevearc/overseer.nvim",
    config = function()
      require("overseer").setup({
        -- add your overseer config here
      })
    end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by matu3ba** [comment]
> Save the task by giving empty string to the bundle name

I think 1. this should print an 1 line error message in cmdline window and 2. the bundle name should be prefilled, if the intended semantics or a bundle is "complete current context".

If a bundle should have semantics of "some commands user provides", then it should be editable via command meaning a command to open dir where bundles are stored should exist.

Not 100% sure, but I'm pretty sure that I did observe the error also reproduces if one uses the same bundle name.

**Comment by stevearc** [comment]
There is some admittedly confusing behavior when you provide an empty name for the bundle, and I have fixed that (empty name is the same as canceling).

The main point in this issue seems to be that you expect task bundles to function kind of like how many people use a session manager. You save a bundle, then whenever you edit and save tasks they "remember" which bundle they were saved to and will update themselves. This is not how task bundles work.

Task bundles are built around two very simple operations: **serialize and save** one or more tasks to disk, and **load tasks from disk** and rehydrate them. There is one _additional_ operation which is you can select an individual task and either save just that task to a new bundle or append it to an existing bundle. Honestly, I don't even use this feature anymore. I find myself creating per-directory tasks with exrc any time I want to start tasks I had running previously. The serialization/deserialization logic is still useful because I use it with sessions all the time, but I never interact directly with bundles.

I would be interested in hearing a bit more about your workflow and what you're trying to accomplish. I won't make any promises, but it's possible there's some change worth making to support it.

**Comment by s1n7ax** [comment]
I'm just working on some devcontainer features. I'm running test cases on change with Overseer. 

Workflow

1. Open neovim
2. Create overseer task for running the feature I'm working on right now

```shell
devcontainer feature test -f <feature_name> -i ubuntu:latest
```

3. Add watch option
4. Save the task
5. Continue working on it for few days
6. Once the feature is done, create a new feature
7. Edit the testing task to the new feature name
8. Save the task (This is where it's failing)
9. Continue working on the feature for few days

All the features are in the same project root. So I have only one bundle. I just think it would be nice to update the task without having to worry about it's bundle name.

**Comment by stevearc** [comment]
Yeah, I think this is a bit too specific to add any features for in core. I don't want to start trying to turn the task bundles into "sessions". But the good news is that you should be able to! If you only have a single bundle that you really use, or you only have one-per-directory, you can make your own keymaps or user commands:

```lua
vim.keymap.set("n", "<leader>bs", function()
  local bundle_name = vim.fs.basename(vim.fn.getcwd())
  require("overseer").save_task_bundle(bundle_name, nil, { on_conflict = "overwrite" })
end)
vim.keymap.set("n", "<leader>bl", function()
  local bundle_name = vim.fs.basename(vim.fn.getcwd())
  require("overseer").load_task_bundle(bundle_name)
end)
```
