### ISSUE TITLE
feature: support preserving focus with on_result_diagnostics_quickfix

### ISSUE THREAD

**Issue by jpetrie** [stevearc/overseer.nvim#234]
Using `on_result_diagnostics_quickfix` with `open` set to `true` causes the quickfix list to open and take focus, which can be distracting. I'd like to be able to configure Overseer to keep (or specifically, restore) the focus to the previous window once the quickfix list is opened. I don't see a way to do this currently, but digging around the source it looks like the desired behavior is obtainable simply by appending `" | wincmd p"` to the command used to open the list.

Plumbing this through properly (with an option such a `keep_focus` that defaults to `false` to preserve existing behavior) doesn't seem that involved, so if this is a feature that seems acceptable I'd be happy to send a PR for it. If on the other hand there's a way to do this already that I've missed, please let me know.

**Comment by stevearc** [comment]
Adding another parameter to control this sounds reasonable. It may be more complicated than just adding `wincmd p` because if the quickfix is already open prior to that command, we don't want to switch back to the previous window. Might make more sense to just store current window and restore it via lua API

**Comment by jpetrie** [comment]
#237 was merged and addresses this. Thank you!
