### ISSUE TITLE
feature request: ToggleTerm respect theme transparency

### ISSUE THREAD

**Issue by ls-devs** [stevearc/overseer.nvim#255]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

Hi,
Actually when openning toggleterm/shell it looks like this : 
![image](https://github.com/stevearc/overseer.nvim/assets/58638832/faaaa549-a689-4dc4-ae04-2b4616d18d1b)

It doesn't respect my theme transparency and I can't find any solution to make it.

### What is the significance of this feature?

nice to have

**Comment by stevearc** [comment]
There's no real concept of "theme transparency" for Neovim, because there's no way to configure global floating window transparency. The transparency is set on a per-window basis by whatever plugin is opening that float. For overseer, you can configure this by setting the `:help winblend` window option on the form. There's a place for this in the setup config table:

```lua
require("overseer").setup({
  form = {
    win_opts = {
      winblend = 100,
    },
  },
})
```
