### ISSUE TITLE
Question: where to add tasks to?

### ISSUE THREAD

**Issue by AntonC9018** [stevearc/overseer.nvim#296]
I want to know if there's some global or not global task list I can append to, without putting the task definition in either a special directory or in `tasks.json`, which are the only methods documented. I just want to imperatively append a default task to the task list when I set up dap.

**Comment by AntonC9018** [comment]
I've tried looking through the code, but it's not as straightforward

**Comment by axelhj** [comment]
Hi! I had a similar issue; I wanted to use a global task-file of sorts for cmake without interacting with the Overseer task list at all. I invoke shell-oneliners by number 1 - 8 on Windows with the following snippet, substitute `name`, `cmd` and `args` for whatever.

They can be restarted from the task list once they are created, otherwise each task will appear once for each invocation (it doesn't seem to clear old tasks of the same name when creating a new task).

```
    require"overseer".new_task({
      cmd = { "cmd.exe" },
      name = "shell " .. n,
      args = { "/c", commands[n] },
      components = { "default" },
      strategy = {
        "toggleterm",
        auto_scroll = true,
        cwd = vim.api.nvim_command"pwd"
      },
    }):start()
```

It doesn't match with the [guide recommendations](https://github.com/stevearc/overseer.nvim/blob/master/doc/guides.md#custom-tasks) but it's working great for me, maybe that would solve your use case too.

Regards

**Comment by stevearc** [comment]
The guide for [custom tasks](https://github.com/stevearc/overseer.nvim/blob/master/doc/guides.md#custom-tasks) mentions two methods that you can use: [overseer.register_template](https://github.com/stevearc/overseer.nvim/blob/master/doc/reference.md#register_templatedefn) and [overseer.load_template](https://github.com/stevearc/overseer.nvim/blob/master/doc/reference.md#load_templatename)
