### ISSUE TITLE
feature request: set the `open_output` component by default

### ISSUE THREAD

**Issue by Zeioth** [stevearc/overseer.nvim#310]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

Focus should go to the latest started task by default.

### Provide background

I'm opening this so we can close #299 #302 and https://github.com/Zeioth/compiler.nvim/pull/45#issuecomment-2151936487

### What is the significance of this feature?

nice to have

**Comment by stevearc** [comment]
I've been thinking about this for a while, and I don't think we want to add `open_output` to all tasks by default. It's a pretty big UX change, and it would default to applying to _all_ tasks. I think for a new user this might be fine, and obviously it helps in your situation, but it has the potential to be really quite disruptive for existing users of overseer. Imagine you have a workflow all nice and customized, and then you upgrade and windows start appearing all over the place. Now you have to dig through the commit history and/or documentation to figure out *why* this is happening so you can disable it. Multiply that by the number of existing users of overseer, and I don't think that amount of thrash is worth the benefit to new users.

In the example PR that I sent you, I demonstrated how you can accomplish this on your side by defining your own component alias and using that for the tasks that you create. It's a bit more work for you because you'll have to update all the locations where you create tasks, but it will have the same effect.

**Comment by Zeioth** [comment]
Thank you for considering it Steve. Ok let's go with the PR way. I'd rather avoiding introducing the concept of components into `compiler.nvim` in order to reduce complexity, buuut it shouldn't be a super big deal probably.
