### ISSUE TITLE
bug: tasks dispose inconsistently

### ISSUE THREAD

**Issue by Zeioth** [stevearc/overseer.nvim#315]
### Neovim version (nvim -v)

0.10.0

### Operating system/version

arch linux

### Describe the bug

Tasks do not dispose consistently:

* Some times tasks are not disposed.
* Orchestrators are not disposed anymore at all.

![screenshot_2024-06-10_12-45-41_027391651](https://github.com/stevearc/overseer.nvim/assets/3357792/8360729e-b8b2-4353-8f87-2fa21e7b6920)

### What is the severity of this bug?

minor (annoyance)

### Steps To Reproduce

1. on unix, and having compiler.nvim installed run `:luafile ~/.local/share/nvim/lazy/compiler.nvim/tests/tests.lua`. This will spawn ~100 tasks over 1 minute (don't worry if some fail due to not having the [required dependency](https://github.com/Zeioth/Compiler.nvim/wiki/how-to-install-the-required-dependencies) installed).
2. wait 300s until tasks start to dispose.

You will see they don't dispose correctly like they used to.

### Expected Behavior

All tasks and orchestrators dispose after 300s.

### Additional context

Hopefully I don't have to bother you much more after this one. But it seems to be a bug.

**Comment by stevearc** [comment]
This is likely due to this change 916263159f5e1ab85f1ee10456fe651f8665c4f5, and is mostly intentional.

The default behavior of the `on_complete_dispose` component did not change, but I _did_ change the default configuration. In brief, it won't dispose until the output buffer has been viewed. This is something that can be configured by end users by customizing the components in the `default` section (removing the `require_view` section). If you want to enforce it more directly in your plugin you can specify the `on_complete_dispose` component and put it before the `default` group so that its settings take priority. I'll open a PR as example

**Comment by Zeioth** [comment]
@stevearc The tasks dispose now indeed, but the orchestrators are not dispose anymore like they used to.

## Before disposing trigger
![screenshot_2024-06-11_01-23-40_988485089](https://github.com/stevearc/overseer.nvim/assets/3357792/05c50221-9820-47a9-a7a9-09546880b8b2)

## After disposing trigger
![screenshot_2024-06-11_01-18-27_565361010](https://github.com/stevearc/overseer.nvim/assets/3357792/d1030759-d73b-4c18-afd6-a871a101e2c4)

**Comment by Zeioth** [comment]
Do I also have to add the component to the orchestrator? If so that's gonna add a big chunk of boilerplate, I'm gonna try tomorrow.

**Comment by Zeioth** [comment]
Yeah indeed... that was the issue. if this is the case, `compiler.nvim` is gonna have to tell its users to add this to their config
```lua
component_aliases = {
  -- Components included in default will apply to all tasks
  default = {
    { "display_duration", detail_level = 2 },
    "on_output_summarize",
    "on_exit_set_status",
    "on_complete_notify",  -- comment this to disable notifications
    { "on_complete_dispose", timeout=300 },
    "open_output"
  },
},
```
* Because otherwise users wouldn't have control over the timeout.
* Also I just noticed we can do the same for, "open_output" and that way we don't need to add components to our code at all, which is great for code maintainability.

**Comment by Zeioth** [comment]
This can be closed now but there is something I've noticed if you are interested:

* With your current default overseer config: After the timeout trigger, if a task hasn't been seen by the user, it will never be disposed. Maybe the timeout should refresh after the user focus the task.
* Also, because users have no reason to click the orchestrator, it normally won't be disposed. 

I would advice against this default, and going back to the old  `on_complete_dispose` by default.

**Comment by stevearc** [comment]
> After the timeout trigger, if a task hasn't been seen by the user, it will never be disposed.

This shouldn't be the case. We start a repeating timer for exactly this reason, and I tested this a few times with a short timeout. Once the user views the task, it gets disposed when the timer next runs https://github.com/stevearc/overseer.nvim/blob/6271cab7ccc4ca840faa93f54440ffae3a3918bd/lua/overseer/component/on_complete_dispose.lua#L70-L79

If you have a reliable repro, could you file it as a bug?

> Also, because users have no reason to click the orchestrator, it normally won't be disposed.

I think this is fine. The pitfall I wanted to avoid is when a user starts a task that takes a while (one or more minutes), gets busy doing something else, then when they think to check back up on it, it has already been disposed and it's impossible to check the output or even see the status. That's a pretty bad experience that I've personally encountered several times. On the other side, if you have a task or set of tasks that you don't care about preserving the output of, there are a number of ways to adjust the components to get that behavior.

**Comment by Zeioth** [comment]
@stevearc I've recorded a video demo: https://www.youtube.com/watch?v=BCgMkNAN4Gs

**Comment by stevearc** [comment]
I've added some additional debug logging to the `on_complete_dispose` component that should help us visualize what's going on under the hood. You can set the debug log level using a configuration like this:
https://github.com/stevearc/dotfiles/blob/e575933206ccdcb0037c66aad50fab9cfb53d49a/.config/nvim/lua/plugins/overseer.lua#L37-L47

Another useful tool in debugging is pulling up the "task edit" window by pressing `<C-e>` when your cursor is on top of a task. That will show you what components are on the task _and_ what their parameters are. I used this to confirm the parameters of the `on_complete_dispose` component when looking at a task.

I am not sure exactly what is happening in your video. I tried to replicate it (using a shorter timeout, because I do not have the patience you do), and the tasks seem to dispose correctly. One thing that I did have to change was the orchestrator tasks were being created with the default components; I had to also set them to use `default_extended` in order to pick up the new timeout value for `on_complete_dispose`. Using this minimal change on https://github.com/stevearc/compiler.nvim/commit/bb6ef3805b543b2546195891acb7b9915415a802, they seem to dispose properly.

If you're still seeing dispose issues, try to get me a minimal init.lua config that will reproduce the issue. It's possible there's some difference in our configs that accounts for the difference.

**Comment by Zeioth** [comment]
I've been testing with [this minimal_file](https://pastebin.com/i8p9XGkT) and it's weird:

## What it works
The component
```
overseer.register_alias("default_extended", {
  { "on_complete_dispose", require_view={}, timeout=10}, -- dispose after 10 secs if the task has been seen.
  "default",
  "open_output", -- focus last executed task
})
Correctly dispose all tasks (they are guaranteed to have been seen because of `open_output`)
```

## What doesn't work
The same component but without  `{ "on_complete_dispose", require_view={}, timeout=10}`.

After the default 300 seconds, tasks are disposed inconsistently, or not at all.

## What doesn't work (neither)
The same component but without  `open_output`
```
overseer.register_alias("default_extended", {
  { "on_complete_dispose", require_view={}, timeout=10},
  "default",
})
```
And then manually executing `:OverseerToggle` should ensure tasks haven't been seen. But all tasks are disposed after 10 seconds anyway.

## More info
This is very weird because according to the [source code of the on_complete_dispose](https://github.com/stevearc/overseer.nvim/blob/master/lua/overseer/component/on_complete_dispose.lua) component, we are doing the same thing as the default, the only thing changing is the timeout (from 300s to 10s)

**Comment by stevearc** [comment]
Okay let's take this case by case

## Case 1
```lua
{
  { "on_complete_dispose", require_view={}, timeout=10},
  "default",
  "open_output",
}
```
This **disposes** all the tasks after 10 seconds. Great, this is the expected behavior.

## Case 2
```lua
{
  "default",
  "open_output",
}
```
This **doesn't dispose** all the tasks. This is _also expected_. The reason is that the `default` group adds a component to the task that requires the user to view the output buffer for successful or failed tasks.
https://github.com/stevearc/overseer.nvim/blob/d78fa84c06d37b1eb3bd42b4b5467c7476e74589/lua/overseer/config.lua#L152

Each task has `open_output`, sure, but this component enforces that the output has been viewed _after_ the task has completed. These buffers have _not_ been viewed after completing.

## Case 3
```lua
{
  { "on_complete_dispose", require_view={}, timeout=10},
  "default",
}
```
This **disposes** all the tasks after 10 seconds. This is _still expected_. By passing in `require_view={}` you are saying "don't require that the task output be viewed before you can dispose this task". As a result, the 10 second timer starts immediately after the task completes, and then they are disposed.

## Solution

I think what you are probably looking for is
```lua
{
  -- Because of the default values this is equivalent to
  -- { "on_complete_dispose", require_view={} }
  "on_complete_dispose",
  "default",
  "open_output",
}
```
This uses the default 300 second timer, and doesn't require that the output buffers are viewed before they can be disposed. If you are still experiencing unexpected behavior, try increasing the log level and inspecting the logs. That should help you figure out what's going on.

You can set the log level using:

```lua
require("overseer").setup({
  log = {
    {
      type = "echo",
      level = vim.log.levels.WARN,
    },
    {
      type = "file",
      filename = "overseer.log",
      level = vim.log.levels.DEBUG,
    },
  },
})
```

**Comment by Zeioth** [comment]
Closing this for now because I'm not gonna have time to test it for a month or so and I don't want to pollute the bug tracker. I'll re-open in the future if I'm able to provide more detail.
