### ISSUE TITLE
bug: performing action automatically changes mode to Insert mode

### ISSUE THREAD

**Issue by suvasanket** [stevearc/overseer.nvim#347]
### Neovim version (nvim -v)

0.10.1

### Operating system/version

14.4

### Describe the bug

When doing quick actions like restart or watch it constantly changing the mode to insert mode even if I'm not in insert mode

### What is the severity of this bug?

minor (annoyance)

### Steps To Reproduce

:OverseerQuickAction restart

### Expected Behavior

Don't change the vim mode

### Minimal init.lua

```Lua
{
		"stevearc/overseer.nvim",
		keys = {
			{ "<leader>cc", "<cmd>OverseerRunCmd<cr>", desc = "run cmd" },
			{ "<leader>ct", "<cmd>OverseerToggle<cr>", desc = "overseer" },
		},
		opts = {
			dap = false,
			task_list = {
				bindings = {
					["<C-u>"] = "ScrollOutputUp",
					["<C-d>"] = "ScrollOutputDown",
					["<C-q>"] = "q<cmd>OverseerQuickAction open output in quickfix<cr>",
					["r"] = "<cmd>OverseerQuickAction restart<cr><esc>",
					["x"] = "<cmd>OverseerQuickAction dispose<cr>",
					["w"] = "<cmd>OverseerQuickAction watch<cr>",
				},
			},
		},
	},
```

**Comment by melMass** [comment]
Yep it would be nice to avoid that. My guess is that it's because of the TermEnter autocmd that does this

**Comment by stevearc** [comment]
Please use a minimal `init.lua` file that is a _complete_ config, as referenced in the bug report template.

**Comment by melMass** [comment]
Well I just did here ([reproduction](https://github.com/melMass/reproduction/tree/nvim/overseer-insert-issue)) but it doesn't do it in isolation 😅 ... 
I'll try to find where it comes from and report here if I ever found out

**Comment by monkoose** [comment]
Not sure if it is related to the OP, but in my config I have, which was the root of the issue, because overseer opens a lot of terminal windows without actually focusing them. Like `OverseerToggle` or any actions which open terminal buffers.
```lua
vim.api.nvim_create_autocmd({ "BufWinEnter", "WinEnter" }, {
   pattern = "term://*",
   command = "startinsert"
})
```

Not sure if it is possible to fix from plugin side. Maybe checking the mode it is in and if it is in insert mode change it to normal? And for me `:startinsert` seems like a hack and enters insert mode even in non-modifiable buffers.

But from user side there are some solutions to narrow such autocmd to only specific terminal buffers, etc.

**Comment by melMass** [comment]
I'll try your autocmd in my repro I might have a similar one I overlooked in my config, but the one there (termopen) doesn't interfere with overseer

**Comment by suvasanket** [comment]
Yuo the problem was caused by an autocmd configuration. Thanks for pointing it out, and it’s resolved now!
