### ISSUE TITLE
Tmux pane support

### ISSUE THREAD

**Issue by bangedorrunt** [stevearc/overseer.nvim#37]
Hi, is it possible to support Tmux panes using Tmux pane ids or tokens? I see Overseer use built-in terminal but I'd like to run tasks and commands in a Tmux pane.

**Comment by stevearc** [comment]
There is currently no support for tmux because overseer relies heavily on having access to the status and output of the task. If there is a way to get that from tmux then it would be possible to write a strategy like the one [for the built-in terminal](https://github.com/stevearc/overseer.nvim/blob/master/lua/overseer/strategy/terminal.lua) and use that instead

**Comment by stevearc** [comment]
Unless I'm missing something, that file appears to be sending lots of commands to tmux, but not reading the output of a long-running process or getting the exit code of a job.
