### ISSUE TITLE
No way to do per-project configuration of templates

### ISSUE THREAD

**Issue by Shatur** [stevearc/overseer.nvim#38]
Is this expected behavior?
In [session-managers](https://github.com/stevearc/overseer.nvim#session-managers) section you mention loading bundle on session load. But the plugin runs a task once I open a session.
I was thinking of using this functionality to save the changes that I made to the tasks (for example, added additional arguments). Am I misusing this feature? If yes, what can I do to provide a project-specific flags?
Or should I use something like https://github.com/windwp/nvim-projectconfig? It's not very convenient since I have to edit my config to adjust tasks.

**Comment by stevearc** [comment]
From the description, it sounds like you may be trying to use those commands for something they were not designed for, but let's check.

What `OverseerSaveBundle` does is take all the current tasks (including the ones that are no longer running) and saves their configuration to a json file. You can also do this on a task-by-task basis using the "save" action, or by calling the API directly with just the tasks you want saved. When you `OverseerLoadBundle`, those specific task configurations are loaded from json, hydrated, and started.

Could you provide a bit more detail about your workflow? At a high level, what are you trying to accomplish and why?

**Comment by Shatur** [comment]
Oh, got it. Then I definitely used it wrong.
I have a Rust project where I set `--features=bevy/dynamic` during development to speedup build times. I can select a cargo task from template, edit it and use it. But I would like to make this option persistent for this project. So I need to serialize it on disk when I save my session and restore it on loading. But looks like `OverseerLoadBundle` is not what I need.

**Comment by stevearc** [comment]
Makes sense. At the moment, I think the best way to do that would be to use something like nvim-projectconfig and to `overseer.hook_template` when you're in that directory. I'm not totally happy with that solution as it's a lot of manual work and doesn't handle cases like using `:tcd` for tab-local projects.

One possible approach would be to allow the hooks to be conditional (e.g. only run in this directory). That would be better, but still require nvim-projectconfig. I think that a "project settings" plugin is going to be required in any case because I've been taking a pretty strong stance against including that kind of logic in overseer.

**Comment by Shatur** [comment]
Got it, thanks!

**Comment by stevearc** [comment]
Let's leave this open for tracking until I get a better solution for this

**Comment by stevearc** [comment]
I've added the ability to specify conditions for template hooks. Lots of docs added, but for your use case this should work:
```lua
overseer.add_template_hook({
  dir = "/path/to/my/project",
  module = "^cargo$",
}, function(task_defn, util)
  task_defn.args = vim.list_extend(task_defn.args or {}, {"--features=bevy/dynamic"})
end)
```

**Comment by Shatur** [comment]
Thanks!
