### ISSUE TITLE
customizable timeout for template initialization?

### ISSUE THREAD

**Issue by emmanueltouzery** [stevearc/overseer.nvim#43]
Hello, following the elixir mix PR, I noticed that the elixir tasks are not always displayed. I tracked it down to the one overseer setting which is not configurable :D that is, the template init timeout:
https://github.com/stevearc/overseer.nvim/blob/master/lua/overseer/template/init.lua#L395

Sadly, `mix help` takes most of the time for me 0.7s, but it does go over 1s quite often... If we changed the code to take an override timeout through `opts`, I could call the overseer functions manually, passing a custom timeout, instead of calling the provided vim command. I could send a PR to that effect, but would you accept it? Or can you think of a better approach...

In the PR you mentioned possible future caching for these settings, but cache invalidation would not be trivial, because in elixir you can add tasks outside of the main exs file, and the timestamp of that file would not be updated. So I guess in my case increasing the timeout is probably the best I can do, bar manual cache invalidation (which actually would be ok in my case, i guess).

What do you think about that?

**Comment by emmanueltouzery** [comment]
In a perfect world, we would populate the list as the results come, so they would tickle in asynchronously, but I don't believe it would be possible with a reasonable amount of effort in a neovim plugin.

**Comment by emmanueltouzery** [comment]
Yet another alternative could be that instead of dynamically loading tasks, there is a function to generate tasks from elixir tasks, that the user may run manually. I believe overseer could support that. In that case display would be instant, but discovery worse. Maybe overseer could say something like "elixir project detected, consider importing tasks by running xxx"

**Comment by stevearc** [comment]
> instead of dynamically loading tasks, there is a function to generate tasks from elixir tasks, that the user may run manually

I think that functionally this would be the same as caching, so I'd prefer caching since it can be generalized.

> In a perfect world, we would populate the list as the results come

This is doable, but not with the current API for `vim.ui.select`, unfortunately. Going down this road would mean a lot of custom code for one specific selection frontend.

For the time being I'll make the timeout a config option; that should unblock you. I'll make the template caching logic a priority since this is starting to matter more. I'll be trapped on a plane for 8 hours on Saturday, so I might be able to do it then.

**Comment by emmanueltouzery** [comment]
> I think that functionally this would be the same as caching, so I'd prefer caching since it can be generalized.

it's the same as caching except that for caching to work, the user might have to increase the timeout the first time? Unless if, thanks to caching, you enable to remove the timeout "the first time", or something like that.

Otherwise sounds like a great plan! :+1:

**Comment by stevearc** [comment]
Whelp, it was a productive flight! If any provider takes longer than 100ms (configurable with `template_cache_threshold`), the results will be cached for the next run. There is some amount of smart cache clearing (e.g. if you write a Makefile, it will clear the cache for that Makefile), but it won't handle all cases (as you mentioned, a lot of files could impact the commands available to `mix`). You can add your own custom cache handling logic with [preload_task_cache](https://github.com/stevearc/overseer.nvim/blob/master/doc/reference.md#preload_task_cacheopts-cb) and [clear_task_cache](https://github.com/stevearc/overseer.nvim/blob/master/doc/reference.md#clear_task_cacheopts). You can also use the [OverseerClearCache](https://github.com/stevearc/overseer.nvim/blob/master/doc/reference.md#commands) command to manually clear the cache.

I've also bumped up the default timeout, since long waits should only happen once now. Also, we cache the results of the provider even if it times out.

**Comment by emmanueltouzery** [comment]
:tada: great! it works great and is super helpful. thanks a lot. and thanks again for overseer in general. I also wrote a custom component to parse the output of a build watcher we have, does marvels!

i'll close this issue, as I consider it fixed, but if you prefer to reopen it for your own needs, feel free of course!

thanks again!
