### ISSUE TITLE
Remove extra empty quickfix output

### ISSUE THREAD

**Issue by petobens** [stevearc/overseer.nvim#45]
Hi! I have a `run_script.lua` template file with:
```lua
return {
    name = 'Run Script',
    builder = function()
        local file = vim.fn.expand('%:p')
        return {
            cmd = { vim.bo.filetype },
            args = { file },
            -- default_component_params = {
            --     errorformat = set_efm(vim.bo.filetype),
            -- },
            components = {
                'default',
                { 'on_output_quickfix', open = true },
            },
        }
    end,
    condition = {
        filetype = { 'python', 'bash', 'lua' },
    },
}
```
and an overseer config file with:
```lua
local overseer = require('overseer')
local u = require('utils')

overseer.setup({
    templates = { 'builtin', 'user.run_script' },
})

-- Mappings
u.keymap('n', '<F7>', function()
    vim.cmd('silent noautocmd update')
    overseer.run_template({ name = 'Run Script' }, function()
        vim.cmd('cclose')
    end)
end)
u.keymap('n', '<Leader>lt', '<Cmd>OverseerQuickAction open hsplit<CR>')
```
Now if, as in the GIF, I do:

1. Press`F7` on a python file with `print(2)` in it then the `2` is printed to the quickfix but there are also 4/5 empty lines with `||`
2. If I remove/comment out the `print(2)` and press `F7` again then the quickfix opens but is empty

My questions therefore are:
a. Is it possible to trim empty quickfix lines such that for case 1. above only `2` is printed/shown in the quickfix
b. Is it possible to add a setting such that when the quickfix is empty (i.e all `text` fields qf entries are empty) then the quickfix doesn't open?
c. (Bonus) Can I use overseer to run over a visual selection of code? (rather than the whole file)? 
d. (Bonus II) Is it possible to simply run a command and then parse a resulting logfile and load the results into the quickfix? i.e I want to simply run a script and once that script finishes parse a log fie

Thanks in advance (neat plugin!)

![overseer](https://user-images.githubusercontent.com/2583971/194795259-2b349928-00e6-4abf-a7fd-739ec1fbc6a8.gif)

**Comment by stevearc** [comment]
Good news is yes, there are a lot of customization options available that suit your needs! The reference docs for this component are at [components.md](https://github.com/stevearc/overseer.nvim/blob/master/doc/components.md#on_output_quickfix), which I now realize got a little bit lost during the big documentation refactor I did recently. I'll try to make those more discoverable and also improve the formatting.

> a. Is it possible to trim empty quickfix lines such that for case 1. above only 2 is printed/shown in the quickfix

Yep! This is the `items_only = true` option. This ensures that only matching valid quickfix items will appear in the quickfix, and not _all output_.

> b. Is it possible to add a setting such that when the quickfix is empty (i.e all text fields qf entries are empty) then the quickfix doesn't open?

Again yep! Instead of `open = true`, use `open_on_match = true`.

Note that for both a and b you will need to make sure that the errorformat will match the errors your script produces. From some brief googling, it looks like `{errorformat = "%C %.%#,%A  File \"%f\"\\, line %l%.%#,%Z%[%^ ]%\\@=%m"}` might work. If the errorformat is not specified in the component, then it will take your global `vim.o.errorformat`. This can be more convenient if you work in multiple languages, as you can set the option based on your filetype or current project (either directly or by using `:compiler`).

> c. (Bonus) Can I use overseer to run over a visual selection of code? (rather than the whole file)?

Sort of, but probably not. Overseer is generic enough that it can run nearly anything that fits the loose definition of "task", but for running a visual selection of code there is already a fantastic plugin called [sniprun](https://github.com/michaelb/sniprun) that does that better than overseer ever could. There's the possibility that overseer could do some sort of integration with sniprun (like we do with neotest), but I'm not yet sure what value we could add there (I don't personally find myself needing or using this feature, so it's not an area I know much about). I'd recommend giving sniprun a try, and if you can think of ways that it would be better if it were somehow integrated with overseer, let me know!

> d. (Bonus II) Is it possible to simply run a command and then parse a resulting logfile and load the results into the quickfix? i.e I want to simply run a script and once that script finishes parse a log fie

This is possible, but not with the built-in components. It is possible to write this on your own, however:

```lua
local function parse_logfile(filename, errorformat)
  local content = require('overseer.files').read_file(filename)
  local lines = vim.split(content, '\n')
  local items = vim.fn.getqflist({
    lines = lines,
    efm = errorformat, -- If nil, this will default to the option value
  }).items
  -- Filter out anything that doesn't match
  local valid_items = vim.tbl_filter(function(item)
    return item.valid == 1
  end, items)
  vim.fn.setqflist({}, ' ', {
    title = 'My log file',
    items = items,
  })
end
```
This is the core logic you would need. You could build this into a new component, or add it as an action, or simply add a task subscriber to run it when the task finishes.

**Comment by petobens** [comment]
Thank you very much for all the help (and sorry for the long delay in my reply). I'll let you know if I have any issues implementing my desired workflow following your pointers.
Feel free to close if you deem fit.

**Comment by stevearc** [comment]
Closing for now, if you have more requests or questions, feel free to open a new issue

**Comment by petobens** [comment]
I'm doing a follow-up here because it's related with the above (I can open a new issue if you want). 

So things mostly work great after your pointers but I'm having an issue such that if my current working directory (`/home/pedro/Desktop`)  is not that of the file I'm currently editing (`/home/pedro/Desktop/test-latex`) then when the quickfix opens and I jump to an error I'm taken to a new empty file (see GIF below). If I make the current file directory the working directory then jumping works as expected (since now the quickfix correctly parses the `.tex` file location). So my question is: how can I set the "quickfix working  directory" to that of the current file?

![overseer_pwd](https://user-images.githubusercontent.com/2583971/198914067-105cd82d-faa8-4a83-ba18-177932f6d1aa.gif)

**Comment by stevearc** [comment]
@petobens I've moved the discussion to a new issue and have some questions for you
