### ISSUE TITLE
Kill or warn about tasks when exiting Neovim

### ISSUE THREAD

**Issue by jfpedroza** [stevearc/overseer.nvim#46]
I had a long-running task with Overseer and I forgot about it when closing Neovim. The task was still running, and I had to manually kill it.

Is there a way to kill them automatically or prevent closing with running tasks?

Thanks for the nice plugin!

**Comment by stevearc** [comment]
Hmmmm...this is very interesting. I haven't had any such issues; all the long-running tasks that I use are terminated when I exit neovim. I know that the processes started with `termopen()` are slightly different from those started with `jobstart()`, and in general there has been some iteration on how Neovim handles child processes.

Would it be possible to come up with a minimal script or example where I can reproduce the issue?

**Comment by jfpedroza** [comment]
Ok, so far I have only been able to reproduce it on a very specific case: a make command running a docker command.

The task is killed if run make with a non-docker command, and also when running the docker command directly. However, if I run a make command that runs a docker command, and close nvim, neither the make process nor the docker process is killed.

Tried it with a simple make recipe that runs `docker logs` on a container.

**Comment by stevearc** [comment]
Alright, I'll give that a shot when I get a chance

**Comment by stevearc** [comment]
Well I have some additional information. When vim exits it sends all of its open terminals (opened with termopen) a SIGHUP. Turns out, `make` ignores SIGHUP, though I can't find any documentation about this. This isn't so uncommon, as daemon processes often use SIGHUP to trigger reloading the config from disk, or similar. When you stop the task directly in overseer (with jobstop) it sends a SIGHUP, followed after a short pause by SIGTERM, which does successfully kill it (I believe that is this [KILL_TIMEOUT_MS](https://github.com/neovim/neovim/blob/e11f3655fb3bbedc29e496db26a25e6c83d25baf/src/nvim/event/process.c#L24-L26) at work). Interestingly, processes started with jobstart are killed with SIGTERM on exit. This appears to be an intentional difference in Neovim's handling of PTY child processes. Another interesting inconsistency: when I open a terminal with `:terminal` and run the make command directly, the process receives a SIGHUP signal followed by another SIGHUP sent by the kernel on vim exit, which in this case _does_ correctly kill the process. This last behavior I do not understand.

I've put in some logic that explicitly calls `jobstop()` when vim is exiting. In most cases, this doesn't change anything. If you have a task like `make` that swallows the SIGHUP, it will cause Neovim to hang for about 2 seconds on exit as it cleans up the children. I think this is an acceptable tradeoff for now.

Long-term, I'm thinking of making a different strategy that directly uses `uv.spawn` instead of `termopen()`. That should give us more direct control over handling the child processes.

**Comment by stevearc** [comment]
While investigating a strategy that uses `uv.spawn` I determined that it doesn't make much sense. It would be better to use `jobstart()` because that handles a lot of the process management and cross-platform logic that we would need anyway. Both of the strategies (terminal & jobstart) should use the above logic of waiting for 2 seconds if necessary and then killing child processes.

Please re-open if the original issue is not resolved.

**Comment by jfpedroza** [comment]
The change kills the `make` command, but since what I run is a docker container, the container keeps running on exit.

I don't think there is a way to stop the container as well, so it can be left as-is.

**Comment by willruggiano** [comment]
Related, although I don't think this is strictly the purview of overseer.nvim. Adding comments here in case it sparks additional inspiration.

One of my .vscode/tasks.json entries is:
```json
    {
      "label": "Devenv",
      "type": "shell",
      "command": "devenv",
      "args": ["up"]
    }
```

which starts [devenv](https://github.com/cachix/devenv). When I exit neovim, the process that devenv spawns (in my case: postgres) is still running and I have to manually `pkill -f postgres` to kill it.

I've resorted to a project-local "plugin" in .nvim/devenv.lua:
```lua
local ok, overseer = pcall(require, "overseer")
if ok and not vim.env.NVIM_DISABLE_DEVENV_EXT then
  vim.api.nvim_create_user_command("Devenv", function()
    local devenv = overseer.new_task({
      cmd = "devenv up",
      components = { "default" },
    })
    devenv:start()

    vim.api.nvim_create_autocmd("VimLeavePre", {
      callback = function()
        -- devenv:stop() -- kills devenv but not postgres
        overseer.new_task({
          cmd = "pkill -f postgres"
        }):start()
      end,
    })
  end, { desc = "devenv" })
end
```

**Comment by melMass** [comment]
+1 for adding a way to notify about running tasks
