### ISSUE TITLE
Can it Run more tasks at the same time ？

### ISSUE THREAD

**Issue by srillia** [stevearc/overseer.nvim#50]

**Comment by srillia** [comment]
I ment that ,when a task is running , Can there another task running? As I known ,[asynctasks.vim](https://github.com/skywind3000/asynctasks.vim)  can not! Just run one in the period ,another can't.

**Comment by stevearc** [comment]
Yes! You can absolutely run more than one task at a time.

**Comment by srillia** [comment]
Amazing ! , test it , good job!

**Comment by srillia** [comment]
![image](https://user-images.githubusercontent.com/25891673/196331713-94e3b1a6-1f83-4814-869c-c6a053c7de24.png)
one more question , resize vsplit windows .logs missing parts.

**Comment by stevearc** [comment]
Overseer uses neovim's built-in terminal, which comes with many benefits and some downsides. One of the downsides is that it sets a virtual terminal width, and will not re-flow the layout when the window is resized. That could explain part of what's happening here.

That said, I've never seen exactly what you're showing, where some of the output appears to be _missing_ rather than just squeezed. I'd suggest two things:
1. See if you can reproduce this by opening a `:terminal` and running the command directly, then resizing the windows as you did before. If you see the same problem, you can file an issue directly on the neovim repo and they may be able to fix it.
2. If the first option doesn't work, see if you can get some sort of minimal task that reproduces the issue and post it here. If I can reproduce it, I might be able to figure something out.
