### ISSUE TITLE
Dap and `.vscode/launch.json`

### ISSUE THREAD

**Issue by ten3roberts** [stevearc/overseer.nvim#52]
I just discovered yet another of your awesome plugins.

I am working on a shared codebase with colleagues using vscode.

I managed to get `:OverseerRun` to pick up and run tasks in `.vscode/tasks.json`. However, debug tasks inside `.vscode/launch.json` are not listed, and I do not know if that is the intention or if a picker should show up on `dap.continue`, as it is not quite clear from the docs. https://github.com/stevearc/overseer.nvim/blob/master/doc/third_party.md#dap

Looking at the code it looks like only `tasks.json` is loaded.

https://github.com/stevearc/overseer.nvim/blob/ab630ed6f8d1e0aba40d434e32d8c84936cbb278/lua/overseer/template/vscode/init.lua#L218-L225

Any help would be appreciated.

# Setup
```lua
require "config.dap"
local overseer = require "overseer"
overseer.setup {
  dap = true,
}

overseer.add_template_hook({}, function(task_defn, util)
  util.add_component(task_defn, { "on_output_quickfix", open = true })
end)

vim.api.nvim_create_user_command("WatchRun", function()
  overseer.run_template({ name = "test" }, function(task)
    if task then
      task:add_component { "restart_on_save", path = vim.fn.expand "%:p" }
      local main_win = vim.api.nvim_get_current_win()
      overseer.run_action(task, "open vsplit")
      vim.api.nvim_set_current_win(main_win)
    else
      vim.notify("WatchRun not supported for filetype " .. vim.bo.filetype, vim.log.levels.ERROR)
    end
  end)
end, {})
```

`config.dap`
```lua

dap.configurations.rust = {
  {
    name = "codelldb",
    type = "codelldb",
    request = "launch",

    -- if you change `runInTerminal` to true, you might need to change the yama/ptrace_scope setting:
    --
    --    echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope
    --
    -- Otherwise you might get the following error:
    --
    --    Error on launch: Failed to attach to the target process
    --
    -- But you should be aware of the implications:
    -- https://www.kernel.org/doc/html/latest/admin-guide/LSM/Yama.html
  },
}

dap.adapters.codelldb = require("config.codelldb").get_codelldb()
dap.defaults.rust.exception_breakpoints = { "rust_panic" }


```

**Comment by stevearc** [comment]
Overseer loads tasks from `tasks.json` because, well, that's where VS Code defines tasks. The `launch.json` file [is for debugging configurations](https://code.visualstudio.com/Docs/editor/debugging#_launch-configurations). As such, `launch.json` is read and used by the debugging plugin (nvim-dap). You can see mention of this [in the helpfile](https://github.com/mfussenegger/nvim-dap/blob/e71da68e59eec1df258acac20dad206366506438/doc/dap.txt) (search for load_launchjs). The integration between the two is just that a `launch.json` file can specify a `preLaunchTask` and `postDebugTask` that reference tasks defined in `tasks.json`. Sometimes those can be important for making the debug session work (performing a build, setting up the environment, etc). As such, the integration between nvim-dap and overseer is that overseer provides a way to run those tasks before starting/after stopping the debug session.

To get what you want, I believe you just need to add this to your config:
```lua
require("dap.ext.vscode").load_launchjs()
```

**Comment by ten3roberts** [comment]
Oh, didn't know dap could do that. Thanks for a quick reply
