### ISSUE TITLE
Possible to get failure notifications for watch tasks that don't exit?

### ISSUE THREAD

**Issue by tmerse** [stevearc/overseer.nvim#60]
First: Thanks for this great plugin!

I'd like to know if it is possible to trigger error notifications for watch tasks like `tsc --watch` that won't exit if there is an error case (as reflected in the logs/output).

For scripts that return with an error/success status, everything works as expected.
Unfortunately, I could not find anything regarding this in the documentation.

For the `tsc`-case, just running `tsc` without `--watch` would not be an option as it has worse performance characteristics. 

Thank you.

**Comment by stevearc** [comment]
This is definitely possible, but there isn't a streamlined way to do it yet. I had to build in functionality for tasks like `tsc --watch` in order to properly support VS Code tasks, so a lot of the functionality is already floating around, but not exposed via an intentional API. Take a look at how the [result_vscode_task](https://github.com/stevearc/overseer.nvim/blob/master/lua/overseer/component/vscode/result_vscode_task.lua) component handles `background`.

I'm without a computer for the weekend, but I can take a crack at extracting that logic into a component when I get back.

**Comment by tmerse** [comment]
Thanks replying and the hint. I will take a look.
Having this exposed at the api-level would be nice indeed.
Superb plugin!

**Comment by stevearc** [comment]
I've begun work on this, but there's several steps involved. You can follow along in the linked PR

**Comment by stevearc** [comment]
This led me to making a lot of improvements to overseer and the documentation! The parsers now have support for this type of long-running task, and I was able to expose the VS Code problem matchers via the normal component interface (not using tasks.json). I've written up [specific example docs](https://github.com/stevearc/overseer.nvim/blob/master/doc/parsers.md#parsing-output-from-a-background-watch-task) for parsing the output of `tsc --watch`. You'll also want to check out the new [on_result_notify](https://github.com/stevearc/overseer.nvim/blob/master/doc/components.md#on_result_notify) component to get notifications working the way you want.

As a starting point, you can try:
```lua
  overseer.register_template({
    name = "tsc --watch",
    builder = function()
      return {
        cmd = { "yarn", "tsc", "--watch" }, -- or however you're running tsc --watch
        components = {
          {
            "on_output_parse",
            problem_matcher = "$tsc-watch",
          },
          "default",
          "on_result_notify",
          "on_result_diagnostics",
          "on_complete_restart",
        },
      }
    end,
  })
```

**Comment by tmerse** [comment]
Wow. Christmas came early this year! Works like a charm for the problem I mentioned.
One more loosely related question corresponding to this issue: https://github.com/stevearc/overseer.nvim/issues/59
Working mostly with monorepos, the filepaths denoted in the quickfix window (via `on_result_diagnostics_quickfix`) are off (not relative to current cwd, as my root is always `.git` in conjunction with npm scripts that reside in the project root, but defer to workspace packages.)
I wonder if  `on_result_diagnostics"` can/should be modified analog to https://github.com/stevearc/overseer.nvim/blob/42c89a24c5f3dc13067fa4aee3467cc51125b531/lua/overseer/component/on_output_quickfix.lua#L102-L108 by using `util.run_in_cwd`.

**Comment by stevearc** [comment]
I'm certain that we can make an improvement here, but just to clarify the exact behavior, could you provide me with an example path for each of:
- nvim cwd
- `tsc --watch` cwd
- filepath output by diagnostics
- actual filepath

**Comment by tmerse** [comment]
Sure thing.
I just created a minimum example here: https://github.com/tmerse/monorepo_sample which represents a common node.js monorepo. The only dependency here is `typescript`. I added an error in `foo.ts` on purpose such that `npm run build:watch` will fail.

1. In neovim, I use `airblade/vim-rooter` with `let g:rooter_patterns = ['.git/']`, so my pwd will always point towards the git root. -> `pwd == path/to/git/monorepo_sample`
2. Overseer will detect the root `package.json` and suggests the task `build:watch` on `:OverseerRun`. 
`npm run build:watch -w @packages/testpackage` will run `tsc --watch` inside the `@packages/testpackage`-folder so this will be tsc's cwd. Setups like those should be rather common around monorepos. Issues may also be common (https://stackoverflow.com/questions/58554760/monorepo-with-paths-from-typescript-is-not-working)
3. filePath output inside of quickfix: `src/foo.ts|3 col 1 error| Cannot find name 'a'.`  Here is where it goes wrong, if my cwd is the project root. An easy fix could be the use of absolute paths inside the tsc output but it does not look like it will ever land (https://github.com/microsoft/TypeScript/issues/36221). 

At least for my workflow, cwd will always be the project root (`.git/`).

**Comment by stevearc** [comment]
Okay, here's what I've done:

- Fixed a relative filename parsing issue with `on_output_quickfix` (61268c60137bc6b09e15fee4e0806ad5c5e9823a)
- Fixed relative filename parsing for `on_output_parse` (5092582feb8376d8ed3bad426519ee04522ec1b8)

In both of these cases, "fixed" just means "now parses relative filenames as relative to the task cwd, instead of vim's cwd"

- npm template provider loads tasks from workspaces (d0005bb825567714aa4f642aedd9b79d21a65fd3)

This does not fix the issue when you use the top-level `npm build:watch` task, because overseer has no way of knowing what directory that is going to effectively run in. But now it should also give you a `npm[@packages/testpackage] build:watch` task that will run with `cwd = @packages/testpackage`, and thus all the relative filename parsing should work.

**Comment by tmerse** [comment]
This fully solved the issue. Thank you one more time!
