### ISSUE TITLE
Built-ins not loaded if cargo root is not git root

### ISSUE THREAD

**Issue by ghillb** [stevearc/overseer.nvim#83]
Given a project, where you have the following folder structure:
```
git_root
└── cargo_root
    ├── Cargo.lock
    ├── Cargo.toml
    ├── src
        └── main.rs
```
Then the Overseer built-ins for cargo are not available when you open `main.rs`. Only if you have a git repo in the same directory as `Cargo.toml`, they are. As this setup is probably not that uncommon, I would propose to make them available even if git and cargo root are not the same.

Commands to reproduce:
```bash
mkdir git_root/
cd git_root/
git init
cargo new cargo_root
cd cargo_root/
nvim src/main.rs
:OverseerRun -> no cargo tasks available
:qall
git init
nvim src/main.rs
:OverseerRun -> cargo tasks available
```

**Comment by stevearc** [comment]
The behavior is actually slightly different than that, and has nothing to do with the git root. I'm confused because your steps to reproduce actually do not reproduce what I would expect is your issue. Currently, we search for a `Cargo.toml` file in Neovim's cwd and in parent directories. So if you
```
cd root
# assume cargo_root/Cargo.toml
nvim cargo_root/src/main.rs
```
The tasks will not be available because the Cargo.toml file is in a _subdirectory_ of the current directory. I assume that this is actually the issue that you are having.

I've reworked the cargo task slightly. Now it should first search for Cargo.toml relative to the current open file (if in a rust file), and fall back to searching relative to the current directory.
