### ISSUE TITLE
[Question] Tasks not running external commands

### ISSUE THREAD

**Issue by Irubataru** [stevearc/overseer.nvim#85]
I am trying to set up a task to run a markdown preview for markdown files and I am struggeling a bit. I was thinking the easiest was to use [markdown-preview.nvim](https://github.com/iamcco/markdown-preview.nvim) but I can't figure out how to define a task that only runs lua code and nothing external. I could of course simply do a keybind for this and not use overseer, or use a tool like grip with overseer if this isn't something you intend overseer to be used for. However, it feels like something like this could fit in overseer and that it would be neat to have all background processes in one place. Is there something I am missing?

Love the plugin btw, use it a lot for npm and cargo :heart:

**Comment by stevearc** [comment]
There is not currently a way to run a lua function _as_ a task. The way that would theoretically be done is by implementing a new [strategy](https://github.com/stevearc/overseer.nvim/blob/master/doc/strategies.md). Currently all the strategies have a way to cancel a running task, and they all produce some form of output to display. It's not obvious to me how this would work for any given lua function.

Could you outline a bit more how you want this to work? What is the lua function you would be running, and why do you want to use overseer for it rather than just calling it directly? What overseer features do you want to interact with, and what does your final desired workflow look like?

**Comment by Irubataru** [comment]
The more I think about it the more it might not really fit into overseer. My inital thought when adding markdown preview to my process is "I want to bind this to my 'run project' keybind" which is overseer, and I wondered if I could get it integrated. Since the plugin has a start and a stop command it fealt natural to have these tied to a task I could start and stop in overseer, but I don't really think there is anything besides that I want and thus it doesn't make sense to make something if it doesn't already exist.

Thank you for the clarification.
