### ISSUE TITLE
Specifying debug port

### ISSUE THREAD

**Issue by mawkler** [stevearc/overseer.nvim#99]
I noticed that [the debug port for node is hard coded to be 9229](https://github.com/stevearc/overseer.nvim/blob/42c0d69f505314d6994a84da4e3fcbaf308c1a86/lua/overseer/template/vscode/provider/func/debug_node.lua#L4). Is fetching the port from the `launch.json` difficult to implement? If yes, could we perhaps work out a temporary fix the user to set the debug port?

**Comment by stevearc** [comment]
Oh wow, first question: are you currently using the Azure func tasks and do they work? I added support for it upon request by someone on Reddit (mostly to make sure the tasks.json support was flexible enough to support extensions), but they never followed up and I've never used Azure so I couldn't test it myself.

It shouldn't be too difficult to read from the `launch.json` config. Could you provide me with a stripped-down example of what your `launch.json` looks like and maybe one or two of the tasks in your `tasks.json`? Seeing a concrete example of how people are actually using it would help a lot.

**Comment by mawkler** [comment]
> I added support for it upon request by someone on Reddit

That was probably me lol. I apoligize for not following that up. I did give it a short try but couldn't immediately get it to work, and other things came in the way so I didn't actually try out properly until now.

> are you currently using the Azure func tasks and do they work?

I am and I did get it to work after changing the hard coded port to match the one in the `launch.json` that my team is using. So that's really cool! :)

[Here's a simple example](https://github.com/mawkler/azure-functions-minimal) with a [`launch.json`](https://github.com/mawkler/azure-functions-minimal/blob/main/.vscode/launch.json) that gets generated when initializing a new Azure Functions project.

**Comment by stevearc** [comment]
Implemented; give it a try!

**Comment by mawkler** [comment]
Hmmm. After running `require('dap').continue()` and selecting this configuration:

```json
{
  "name": "Attach to Node Functions",
  "type": "pwa-node",
  "request": "attach",
  "port": 9230,
  "preLaunchTask": "func: host start"
}
```

I still see the following in the Overseer output:

```
Debugger listening on ws://127.0.0.1:9229/...
```

Shouldn't it be listening on `ws://127.0.0.1:9230/...`?

**Comment by stevearc** [comment]
So based on the logic here: https://github.com/microsoft/vscode-azurefunctions/blob/411ece5f9453af075c1ff48c70aec349f5942a47/src/debug/FuncTaskProvider.ts#LL145C42-L145C54
It looks like the task implementation for VS Code is setting an environment variable for the specific language. For node, the env variable is name `languageWorkers__node__arguments` and the value will be `--inspect=<port>`.
https://github.com/microsoft/vscode-azurefunctions/blob/a726dec9ebe79b004b9c8e116426ebac9764e754/src/debug/NodeDebugProvider.ts#L22-L30

I don't have `func` set up and running on my local machine, but I tested it by creating a `func` executable that just runs `env | grep languageWorkers`. By inspecting the output, I can see that it is indeed being run with the correct port in the environment variable.

If you're still seeing it running with the default port, then I'd say do a quick check like I did to make sure the environment variable is getting set properly. If it isn't, then there's something going wrong with the environment. If it is, then I'm not sure what the problem is. As always, it's very useful to have a functioning CLI command that you can run that produces the desired output. Once you have that, we can iterate on figuring out the difference between it and what overseer is doing.

**Comment by mawkler** [comment]
@stevearc You're right it does work! I have to restart Neovim for a changed port in `launch.json` to have effect, perhaps that's why I thought it wasn't working 🙂

**Comment by stevearc** [comment]
Great to hear! Overseer reads `tasks.json` on-demand, but I guess `nvim-dap` reads the `launch.json` file once when you call `load_launchjs()`. You would probably have to call that again if you want it to pick up changes in the file.
